# ======== Phasing rope that doesn't collide with anything ======
# Base configuration
- type: ropeConfiguration
  id: Phasing10
  parent: Leash10 # I can't be fucked to make a unique sprite
  links: 10
  linkPrototype: RopeLinkPhasing
  dataPrototype: RopeDataPhasing

- type: ropeConfiguration
  id: Phasing20
  parent: Phasing10
  links: 20

# Link entity
- type: entity
  parent: RopeLinkBase
  id: RopeLinkPhasing
  name: phasing rope link
  categories: [ HideSpawnMenu ]
  components:
  - type: Fixtures
    fixtures:
      fix1: # Needs a fixture to have canCollide: true
        shape:
          !type:PhysShapeCircle
          radius: 0.15
        density: 15
        layer:
        - GhostImpassable

# Data entity
- type: entity
  id: RopeDataPhasing
  parent: RopeDataBase
  name: phasing rope
  description: Doesn't collide with walls.
  categories: [ HideSpawnMenu ]
  components:
  - type: Rope
    color: "#55ffff90" # Semitransparent
    configuration: Phasing10 # required by the yaml linter, updated on spawn


# ======== Antigravity rope (not affected by gravitiy) ======
# Base configuration
- type: ropeConfiguration
  id: Antigravity10
  parent: Leash10 # I can't be fucked to make a unique sprite
  links: 10
  linkPrototype: RopeLinkAntigravity
  dataPrototype: RopeDataAntigravity

- type: ropeConfiguration
  id: Antigravity20
  parent: Antigravity10
  links: 20

# Link entity
- type: entity
  parent: RopeLinkBase
  id: RopeLinkAntigravity
  name: Antigravity rope link
  categories: [ HideSpawnMenu ]
  components:
  - type: MovementIgnoreGravity
    weightless: true

# Data entity
- type: entity
  id: RopeDataAntigravity
  parent: RopeDataBase
  name: Antigravity rope
  description: Isn't affected by gravity.
  categories: [ HideSpawnMenu ]
  components:
  - type: Rope
    configuration: Antigravity10 # required by the yaml linter, updated on spawn
    color: "#55ff5590" # Semitransparent
