- type: entity
  id: RopeBundleBase
  parent: BaseItem
  abstract: true
  components:
  - type: Sprite
    sprite: _Floof/Objects/Tools/rope_bundle.rsi
  - type: Item
    sprite: _Floof/Objects/Tools/rope_bundle.rsi
  - type: RopeConnector
    connectDelay: 3
    detachDelay: 3
    targetWhitelist:
      components:
      - Item
      - Machine
      tags:
      - Crate
    targetBlacklist:
      components:
      - Ghost
      - VirtualItem
  - type: EntityConfiguration
    currentConfig:
      length: 5
    configGroups:
      length:
        name: leash-config-category-length
        options:
        - name: leash-config-length
          value: 10
        - name: leash-config-length
          value: 7.5
        - name: leash-config-length
          value: 5
        - name: leash-config-length
          value: 4
        - name: leash-config-length
          value: 3
  - type: Anchorable
    delay: 3
    snap: false # One day this will work. Not today though.

# Link entity
- type: entity
  id: RopeLinkStandardRope
  parent: RopeLinkBase
  name: standard rope link
  categories: [ HideSpawnMenu ]

# Data entity
- type: entity
  id: RopeDataStandardRope
  parent: RopeDataBase
  name: standard rope
  categories: [ HideSpawnMenu ]


# Rope handle. Does nothing.
# Handles were never implemented and just sit as a to-do for now.
#- type: entity
#  id: RopeBundleBasicHandle
#  parent: BaseItem
#  name: handle
#  description: An end of a rope.
#  categories: [ HideSpawnMenu ]
#  components:
#  - type: Sprite
#    sprite: _Floof/Objects/Tools/rope_bundle.rsi
#    layers:
#    - state: icon
#    scale: 0.7, 0.7
#  - type: Item
#    sprite: _Floof/Objects/Tools/rope_bundle.rsi
