# Standard leash (10 segments), also base for the rest
- type: ropeConfiguration
  id: Leash10
  parent: BaseRopeConfig
  links: 10
  linkPrototype: RopeLinkLeash
  dataPrototype: RopeDataLeash
  sprite:
    sprite: _Floof/Objects/Tools/rope.rsi
    state: rope-simple

# Standard leash (5 segments)
- type: ropeConfiguration
  id: Leash5
  parent: Leash10
  links: 5

# Admeme leash (20 segments)
- type: ropeConfiguration
  id: Leash20
  parent: Leash10
  links: 20

# Leash with 0 segments (pre-update behavior)
- type: ropeConfiguration
  id: Leash0
  parent: Leash10
  links: 0
  stiffness: 0 # Only MaxDistance matters


# Link entity
- type: entity
  parent: RopeLinkBase
  id: RopeLinkLeash
  name: leash link
  categories: [ HideSpawnMenu ]
  components:
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.15 # This should be plenty enough to avoid phasing through walls, i think.
          position: 0,0
        density: 30 # Has to weigh much more to lower jittering. Leashes are used to move specifically kinemic controllers which like to create jitters when moving.
        mask:
        - ItemMask
        restitution: 0.3
        friction: 0.2


# Data entity
- type: entity
  id: RopeDataLeash
  parent: RopeDataBase
  name: leash
  categories: [ HideSpawnMenu ]
