- type: trait
  id: MarkedForDeath
  name: trait-marked-teach-name
  description: trait-marked-teach-desc
  category: Meta
  cost: 0
  usesSlots: false
  conditions:
  - !type:InDepartmentCondition
    department: Command
    invert: true
  - !type:InDepartmentCondition
    department: Security
    invert: true
  - !type:HasCompCondition
    component: TargetObjectiveImmune
    invert: true
  effects:
  - !type:AddCompsEffect
    components:
    - type: Marked
      targetType: Teach

- type: trait
  id: MarkedForRemoval
  name: trait-marked-remove-name
  description: trait-marked-remove-desc
  category: Meta
  cost: 0
  usesSlots: false
  conditions:
  - !type:HasCompCondition
    component: TargetObjectiveImmune
    invert: true
  effects:
  - !type:AddCompsEffect
    components:
    - type: Marked
      targetType: Remove

- type: trait
  id: ConversionImmune
  name: trait-conversion-immune-name
  description: trait-conversion-immune-desc
  category: Meta
  cost: 0
  usesSlots: false
  conditions:
  - !type:IsAntagEligibleCondition
    antag: CosmicAntagCultist # Can you sell faith you can't lose?
    invert: true
  - !type:HasCompCondition
    component: BorgChassis
    invert: true
  effects:
  - !type:AddCompsEffect
    components:
    - type: ConversionImmune
      protectionType: All # If more granular traits get added, make sure to add a new trait effect that adds protection types instead of overwriting them
