# Euphoria - At some point, Delta-V deleted this workflow for some odd reason. We restored it by reversing commit 89faddc9cc8bb4db022ace334b74444cf1f1a56c.
# DO NOT DELETE!!! - M3739
name: PR Changelogs
concurrency: commit_action
on:
  pull_request_target:
    types: [closed]
  workflow_dispatch: # Floofstation
    inputs:
      pr_number:
        description: 'PR number'
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHANGELOG_DIR: ${{ vars.CHANGELOG_DIR }}
  PR_NUMBER: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.pr_number || github.event.number }} # If running manually, fall back to manually specified PR number

jobs:
  changelog:
    runs-on: changelog
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' # Floofstation - permit manual dispatch
    permissions:
      contents: write
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          ref: "${{ vars.CHANGELOG_BRANCH }}"

      - name: Setup Git
        run: |
          git config --global user.name "${{ vars.CHANGELOG_USER }}"
          git config --global user.email "${{ vars.CHANGELOG_EMAIL }}"
        shell: bash

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: |
          cd "Tools/changelog"
          npm install
        shell: bash
        # ontinue-on-error: true # Euph - no

      - name: Generate Changelog
        run: |
          cd "Tools/changelog"
          node changelog.js
        shell: bash
        # continue-on-error: true # Euph - no

      - name: Commit Changelog
        run: |
          git add *.yml
          git commit -m "${{ vars.CHANGELOG_MESSAGE }} (#${{ env.PR_NUMBER }})"
          git push
        shell: bash
        # continue-on-error: true # Euph - no
